server.port=8080

spring.application.name=api-gateway

spring.cloud.gateway.routes[0].id=academic-service
spring.cloud.gateway.routes[0].uri=lb://academic-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/departmani/**,/api/smerovi/**,/api/predmeti/**,/api/materijali/**

spring.cloud.gateway.routes[1].id=users-service
spring.cloud.gateway.routes[1].uri=lb://users-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/korisnici/**,/api/studenti/**,/api/profesori/**,/api/sluska/**

spring.cloud.gateway.routes[2].id=scheduling-service
spring.cloud.gateway.routes[2].uri=lb://scheduling-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/ucionice/**,/api/termini/**,/api/semestri/**,/api/izvodjenje/**

spring.cloud.gateway.routes[3].id=exams-service
spring.cloud.gateway.routes[3].uri=lb://exams-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/ispiti/**,/api/zadaci/**,/api/izvestaji/**

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false

jwt.secret=minimum256bitovaduzinejenestoovako
jwt.expiration-ms=3600000

logging.level.org.springframework.cloud.gateway=INFO
logging.level.com.fakultet.apigateway=DEBUG