server.port=8888
spring.application.name=config-server

# "native" profil = config-repo se cita sa fajl-sistema/classpath-a,
# ne sa Git-a (jednostavnije za lokalni fakultetski projekat)
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=classpath:/config-repo

# config-server sam sebe ne registruje na Eureka (nema potrebe -
# servisi ga zovu direktno preko fiksne adrese http://localhost:8888)
eureka.client.enabled=false
